version: '3'

services:
  employee:
    image: shaunmbolompo297/webapp:2
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - elastic-network
  
  elasticsearch:
    container_name: elasticsearch-container
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - elastic-network
  
  kibana:
    container_name: kibana-container
    image: kibana:7.17.20
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - elastic-network
    
  jaeger:
    container_name: jaeger-container
    image: jaegertracing/all-in-one:latest
    ports:
      - 16687:16687
    networks:
      - elastic-network
  
  sql-edge:
#    build:
#      context: .
#      dockerfile: Dockerfile.sqlimage
    container_name: sql-edge-container
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Password_123
      - MSSQL_PID=Developer
      - MSSQL_USER=sa
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
    networks:
      - elastic-network
    command: ["/opt/mssql/bin/sqlservr"]
    
  
networks:
  elastic-network:
    driver: bridge

volumes:
  elasticsearch-data:
  